export interface ADJUSTMENT {
    "Txnuid": string;
    "Uid": string;
    "Adjdate": string;
    "Adjtype": string;
    "Remitter": string;
    "Beneficiery": string;
    "Response": string;
    "Txndate": string;
    "Txntime": string;
    "RRN": string;
    "Terminalid": string;
    "Ben_Mobile_No": string;
    "Rem_Mobile_No": string;
    "Chbdate": string;
    "Chbref": string;
    "Txnamount": string;
    "Adjamount": string;
    "Rem/PayeePSP_Fee": string;
    "Ben_Fee": string;
    "Ben_FeeSW": string;
    "Adjfee": string;
    "Npcifee": string;
    "Remfeetax": string;
    "Benfeetax": string;
    "Npcitax": string;
    "Adjref": string;
    "Bankadjref": string;
    "Adjproof": string;
    "Compensation amount": string;
    "Adjustment raised time": string;
    "No of Days for Penalty": string;
    "SHDT73": string;
    "SHDT74": string;
    "SHDT75": string;
    "SHDT76": string;
    "SHDT77": string;
    "Transaction_Type": string;
    "Transaction Indicator": string;
    "Beneficiary Account number": string;
    "Remitter Account number": string;
    "Aadhar Number": string;
    "Mobile Number": string;
    "Payer PSP": string;
    "Payee PSP": string;
    "UPI Transaction ID": string;
    "Virtual Address": string;
    "Dispute Flag": string;
    "Reason Code": string;
    "MCC": string;
    "Originating Channel": string;

}